# Copyright © 2026 Josh Burt
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

"""Orchestrates key rotation, re-encryption sweep, and key expiry.

The ``SecretRotationService`` manages the rotate → re-encrypt → expire
lifecycle for the encryption key ring.  Rotation promotes the current
key to previous and generates a fresh current key; the re-encryption
sweep re-encrypts all secrets still referencing the previous key under
the new current key; and expire removes the previous key once no rows
reference it.
"""

from __future__ import annotations

import logging

from ...db.models.user_secret import UserSecret
from ...db.repositories.user_secret_repository import UserSecretRepository
from .._shared.encryption import EncryptionService
from .._shared.encryption_errors import RotationInProgressError, SweepIncompleteError
from .._shared.key_ring import KeyRing

logger = logging.getLogger(__name__)


class SecretRotationService:
    """Orchestrates key rotation: rotate, re-encrypt sweep, and expire previous.

    Parameters
    ----------
    user_secret_repo : UserSecretRepository
        Repository for ``UserSecret`` CRUD operations.
    encryption_service : EncryptionService
        AES-256-GCM encryption service used to decrypt and re-encrypt
        secret values during the sweep.
    key_ring : KeyRing
        Mutable key ring with ``current`` and optional ``previous`` keys.
        The service mutates the ring in-place and persists via
        ``key_ring.save()``.
    """

    def __init__(
        self,
        user_secret_repo: UserSecretRepository,
        encryption_service: EncryptionService,
        key_ring: KeyRing,
    ) -> None:
        self._repo = user_secret_repo
        self._encryption = encryption_service
        self._key_ring = key_ring

    async def rotate(self) -> str:
        """Mint a new key, promoting the current key to previous.

        Returns
        -------
        str
            The new key ID (kid) generated by the key ring.

        Raises
        ------
        RotationInProgressError
            A previous key already exists — the current rotation must
            be completed (sweep + expire) before a new rotation can
            begin.
        """
        if self._key_ring.previous is not None:
            raise RotationInProgressError(
                "Rotation already in progress; previous key must be expired first"
            )
        old_current = self._key_ring.current
        self._key_ring.previous = old_current
        new_kid = self._key_ring.generate()
        self._key_ring.current = new_kid
        self._key_ring.save()
        logger.info("Rotated key: current=%s previous=%s", new_kid, old_current)
        return new_kid

    async def reencrypt_sweep(self, batch_size: int = 100) -> int:
        """Re-encrypt rows with ``key_id=previous`` under the current key.

        Decrypts each secret using the previous key, re-encrypts using
        the current key, and updates the row.  Uses cursor-based
        pagination for crash recovery — re-running skips already-rotated
        rows because their ``key_id`` no longer matches ``previous``.

        Parameters
        ----------
        batch_size : int, optional
            Rows per batch, by default 100.

        Returns
        -------
        int
            Total number of rows re-encrypted and flushed.

        Notes
        -----
        The method is **idempotent**.  Rows whose ``key_id`` has already
        been updated to ``current`` will not be matched by the
        ``previous`` filter on subsequent calls.
        """
        if self._key_ring.previous is None:
            return 0
        processed = 0
        while True:
            rows: list[UserSecret] = []
            async for row in self._repo.iterate_by_key_id(
                self._key_ring.previous, batch_size
            ):
                rows.append(row)
                if len(rows) >= batch_size:
                    break
            if not rows:
                break
            for row in rows:
                aad = f"{row.user_id}:{row.key}".encode()
                plaintext = self._encryption.decrypt(row.encrypted_value, aad)
                row.encrypted_value = self._encryption.encrypt(plaintext, aad)
                row.key_id = self._key_ring.current
            await self._repo._session.flush()
            processed += len(rows)
            logger.info(
                "Sweep batch: %d rows re-encrypted (last row id=%d)",
                len(rows),
                rows[-1].id,
            )
        logger.info("Sweep complete: %d rows processed", processed)
        return processed

    async def expire_previous(self) -> str | None:
        """Remove the previous key from the ring.

        Gated on zero residual rows referencing the previous key.

        Returns
        -------
        str | None
            The expired key ID, or ``None`` if no previous key existed.

        Raises
        ------
        SweepIncompleteError
            One or more rows still reference the previous key.
            The caller must complete the re-encryption sweep before
            expiry.
        """
        if self._key_ring.previous is None:
            return None
        count = await self._repo.count_by_key_id(self._key_ring.previous)
        if count > 0:
            raise SweepIncompleteError(
                f"Cannot expire previous key: {count} rows still reference "
                f"kid={self._key_ring.previous}"
            )
        expired = self._key_ring.previous
        del self._key_ring.keys[expired]
        self._key_ring.previous = None
        self._key_ring.save()
        logger.info("Expired previous key: %s", expired)
        return expired

    def rotation_status(self) -> dict[str, str | None]:
        """Return the current ring state (synchronous, no row counts).

        Returns
        -------
        dict
            A dict with ``current`` and ``previous`` key IDs.
        """
        return {
            "current": self._key_ring.current,
            "previous": self._key_ring.previous,
        }

    async def rotation_status_with_counts(self) -> dict[str, object]:
        """Return the full ring state with per-kid row counts.

        Fetches row counts asynchronously for each key in the ring.

        Returns
        -------
        dict
            Dict with ``current``, ``previous``, and ``rows_by_kid``
            (map of kid → row count).
        """
        result: dict[str, object] = {
            "current": self._key_ring.current,
            "previous": self._key_ring.previous,
        }
        rows_by_kid: dict[str, int] = {}
        for kid in self._key_ring.keys:
            rows_by_kid[kid] = await self._repo.count_by_key_id(kid)
        result["rows_by_kid"] = rows_by_kid
        return result
