sonar.organization=shapeandshare
sonar.projectKey=shapeandshare_anvil
sonar.projectName=anvil
sonar.sources=anvil
sonar.tests=tests
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.exclusions=anvil/_resources/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml